name: docker build and push

on:
  push:
    branches:
      - main
    tags:
      - "**"

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: mambaorg/quetz
    steps:
      - name: Set Docker image for main branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "DOCKER_IMAGES=${IMAGE_NAME}:latest" >> $GITHUB_ENV

      - name: Set Docker image for tag
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        run: echo "DOCKER_IMAGES=${IMAGE_NAME}:latest,${IMAGE_NAME}:${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Show docker images
        run: echo $DOCKER_IMAGES

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGES }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
