name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/provision-with-micromamba@v15
      - uses: pre-commit/action@v2.0.0
        with:
          extra_args: --all-files --show-diff-on-failure
        env:
          PRE_COMMIT_USE_MICROMAMBA: 1
